language: node_js

node_js:
  - 14.15.0

install:
  - yarn install

script:
  - gatsby build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "my-example-website-production"
  skip_cleanup: true
  acl: public_read
  local_dir: public
  on:
    branch: main
